-- =============================================================================
-- Inflaatio.fi – cookieless page-view counter in Supabase (PostgreSQL)
-- =============================================================================
--
-- WHO RUNS THIS: the site owner, once, in the Supabase dashboard
--   (project ysuhexvvgjoizrcdrxso → SQL Editor → New query → paste → Run).
--   Run it BEFORE (or right when) the new site is deployed: the new site sends
--   a `device` column that the old table does not have yet, and inserts fail
--   (silently, the page is not affected) until this script has run.
--   The script is idempotent: running it again is safe.
--
-- WHAT THE SITE SENDS (src/js/lib/analytics.js, one POST per page load,
-- anon key, `Prefer: return=minimal`, no cookies, no ids):
--   { "event_type": "page_view",
--     "page":       "/vuokrankorotus/",   -- canonical path, no query/hash, ≤ 200 chars
--     "referrer":   "direct" | "internal" | "google.com",  -- host name only, ≤ 100 chars
--     "device":     "mobile" | "tablet" | "desktop" }
--   The time comes from the database (created_at default now()).
--   Nothing is sent when the browser has Global Privacy Control / Do Not Track
--   on, outside inflaatio.fi / www.inflaatio.fi, or when inflaatio.fi frames
--   its own page (the widget preview on /upotus/ohje/, URLs with ?esikatselu),
--   so '/upotus/' rows count only real embeds and direct visits. Described to visitors in
--   /kayttoehdot/#kavijatilasto (legal basis: legitimate interest; retention
--   14 months – keep RETENTION_MONTHS in analytics.js and the cron job below
--   in sync).
--
-- WHAT THIS SCRIPT DOES
--   1. Creates the table if it does not exist (fresh project), otherwise
--      migrates the old table: adds `device` and `created_at` (back-filled
--      from the old `date` column), makes the old columns optional
--      (`date` gets a Helsinki-date default and `count` defaults to 1 so old
--      reports keep working), and removes stored search terms from old rows.
--   2. Row level security: anon may INSERT only – exactly the four columns
--      above, `event_type` from a whitelist, length/format checks. anon and
--      authenticated can NOT select, update or delete. (The old table allowed
--      anon to read every row.) You read the data in the dashboard (SQL
--      Editor / Table Editor run as the table owner or service role, which
--      bypass RLS) – never with the anon key.
--   3. Retention: a pg_cron job deletes rows older than 14 months every night.
--
-- AFTER RUNNING – verify from any terminal (ANON = the anon key from
-- src/site.config.js):
--   # must FAIL (401/403 "permission denied") – anon cannot read:
--   curl -s "https://ysuhexvvgjoizrcdrxso.supabase.co/rest/v1/inflaatio_analytics?select=*&limit=1" \
--        -H "apikey: $ANON" -H "Authorization: Bearer $ANON"
--   # must SUCCEED with HTTP 201 and an empty body:
--   curl -s -o /dev/null -w "%{http_code}\n" -X POST \
--        "https://ysuhexvvgjoizrcdrxso.supabase.co/rest/v1/inflaatio_analytics" \
--        -H "apikey: $ANON" -H "Authorization: Bearer $ANON" \
--        -H "Content-Type: application/json" -H "Prefer: return=minimal" \
--        -d '{"event_type":"page_view","page":"/__tarkistus__/","referrer":"direct","device":"desktop"}'
--   # must FAIL (401/403 "violates row-level security policy"):
--   curl … -d '{"event_type":"click","page":"/","referrer":"direct","device":"desktop"}'
--   # must FAIL ("permission denied for … column search_query"):
--   curl … -d '{"event_type":"page_view","page":"/","search_query":"x"}'
--   Then delete the test row in the SQL Editor:
--   delete from public.inflaatio_analytics where page = '/__tarkistus__/';
--
-- ABUSE: the anon key is public by design, so anyone can still insert rows
-- that pass the checks. Retention caps the table size; watch the row count
-- (Dashboard → Database → Tables). If spam appears, move the insert behind a
-- rate-limited Supabase Edge Function and revoke the anon INSERT grant.
-- =============================================================================

begin;

-- -----------------------------------------------------------------------------
-- 1. Table and columns
-- -----------------------------------------------------------------------------

create table if not exists public.inflaatio_analytics (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  event_type  text not null,
  page        text not null,
  referrer    text,
  device      text
);

comment on table public.inflaatio_analytics is
  'Inflaatio.fi cookieless page views (one row per page load: event_type, page, referrer category, device class, created_at). No personal data; retention 14 months (pg_cron job inflaatio-analytics-retention). Written by src/js/lib/analytics.js; schema docs/supabase.sql.';

alter table public.inflaatio_analytics add column if not exists event_type text;
alter table public.inflaatio_analytics add column if not exists page text;
alter table public.inflaatio_analytics add column if not exists referrer text;
alter table public.inflaatio_analytics add column if not exists device text;

-- created_at: add it (old table) and back-fill from the old "date" column
-- (noon Helsinki time of that day); rows without a date get the run time.
do $$
declare
  has_created boolean;
  has_date boolean;
begin
  select exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'inflaatio_analytics' and column_name = 'created_at'
  ) into has_created;
  select exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'inflaatio_analytics' and column_name = 'date'
  ) into has_date;

  if not has_created then
    alter table public.inflaatio_analytics add column created_at timestamptz;
    if has_date then
      execute $q$
        update public.inflaatio_analytics
           set created_at = ((("date"::text)::date + time '12:00') at time zone 'Europe/Helsinki')
         where "date" is not null
      $q$;
    end if;
    update public.inflaatio_analytics set created_at = now() where created_at is null;
  end if;

  alter table public.inflaatio_analytics alter column created_at set default now();
  alter table public.inflaatio_analytics alter column created_at set not null;
end
$$;

-- Old columns the new site no longer sends: optional, with defaults that keep
-- old reports (sum(count) per "date") working.
do $$
declare
  col text;
begin
  foreach col in array array['date', 'count', 'search_query', 'session_duration'] loop
    if exists (
      select 1 from information_schema.columns
      where table_schema = 'public' and table_name = 'inflaatio_analytics' and column_name = col
    ) then
      execute format('alter table public.inflaatio_analytics alter column %I drop not null', col);
    end if;
  end loop;

  if exists (select 1 from information_schema.columns
             where table_schema = 'public' and table_name = 'inflaatio_analytics' and column_name = 'date') then
    execute $q$alter table public.inflaatio_analytics alter column "date" set default ((now() at time zone 'Europe/Helsinki')::date)$q$;
  end if;
  if exists (select 1 from information_schema.columns
             where table_schema = 'public' and table_name = 'inflaatio_analytics' and column_name = 'count') then
    execute 'alter table public.inflaatio_analytics alter column "count" set default 1';
  end if;

  -- Data minimisation: the privacy policy says no search terms are stored.
  -- Remove the ones the old site collected from URL parameters (q, s, utm_term …).
  if exists (select 1 from information_schema.columns
             where table_schema = 'public' and table_name = 'inflaatio_analytics' and column_name = 'search_query') then
    execute 'update public.inflaatio_analytics set search_query = null where search_query is not null';
  end if;
end
$$;

-- Device class values (new column: no old rows to validate).
alter table public.inflaatio_analytics drop constraint if exists inflaatio_analytics_device_check;
alter table public.inflaatio_analytics
  add constraint inflaatio_analytics_device_check
  check (device is null or device in ('mobile', 'tablet', 'desktop'));

-- Reports and the retention job filter by time.
create index if not exists inflaatio_analytics_created_at_idx
  on public.inflaatio_analytics (created_at);

-- -----------------------------------------------------------------------------
-- 2. Row level security and privileges: anon may INSERT only
-- -----------------------------------------------------------------------------

alter table public.inflaatio_analytics enable row level security;

-- Remove every existing policy (the old setup let anon read all rows).
do $$
declare
  pol record;
begin
  for pol in
    select policyname from pg_policies
    where schemaname = 'public' and tablename = 'inflaatio_analytics'
  loop
    execute format('drop policy %I on public.inflaatio_analytics', pol.policyname);
  end loop;
end
$$;

-- No table-level rights for the API roles …
revoke all on table public.inflaatio_analytics from anon, authenticated;
-- … except inserting exactly these four columns (everything else takes its
-- default: id, created_at, date, count; search_query/session_duration stay null).
grant insert (event_type, page, referrer, device) on table public.inflaatio_analytics to anon;

create policy inflaatio_analytics_anon_insert
  on public.inflaatio_analytics
  for insert
  to anon
  with check (
    event_type in ('page_view')                                   -- whitelist of event types
    and page is not null
    and char_length(page) between 1 and 200
    and left(page, 1) = '/'
    and page !~ '[?#[:space:]]'                                   -- path only: no query, hash or spaces
    and (referrer is null or (char_length(referrer) between 1 and 100 and referrer ~ '^[a-z0-9.-]+$'))
    and (device is null or device in ('mobile', 'tablet', 'desktop'))
  );

-- No SELECT / UPDATE / DELETE policies on purpose: with RLS enabled and no
-- policy, anon and authenticated can do none of these (and the grants above
-- do not allow them either).

commit;

-- -----------------------------------------------------------------------------
-- 3. Retention: delete rows older than 14 months (pg_cron, nightly 03:17 UTC)
-- -----------------------------------------------------------------------------
-- pg_cron must be enabled once: Dashboard → Database → Extensions → pg_cron,
-- or run the next statement. cron.schedule() with an existing job name
-- replaces that job, so re-running is safe.

create extension if not exists pg_cron with schema pg_catalog;

select cron.schedule(
  'inflaatio-analytics-retention',
  '17 3 * * *',
  $$delete from public.inflaatio_analytics where created_at < now() - interval '14 months'$$
);

-- Check the job and its runs:
--   select jobid, jobname, schedule, command, active from cron.job where jobname = 'inflaatio-analytics-retention';
--   select status, return_message, start_time from cron.job_run_details
--    where jobid = (select jobid from cron.job where jobname = 'inflaatio-analytics-retention')
--    order by start_time desc limit 5;

-- -----------------------------------------------------------------------------
-- Example reports (SQL Editor; times in Helsinki)
-- -----------------------------------------------------------------------------
-- Page views per day:
--   select (created_at at time zone 'Europe/Helsinki')::date as day, count(*) as views
--     from public.inflaatio_analytics where event_type = 'page_view'
--    group by 1 order by 1 desc limit 60;
-- Top pages, last 30 days:
--   select page, count(*) from public.inflaatio_analytics
--    where event_type = 'page_view' and created_at > now() - interval '30 days'
--    group by 1 order by 2 desc limit 30;
-- Where visitors come from / devices, last 30 days:
--   select referrer, count(*) from public.inflaatio_analytics
--    where event_type = 'page_view' and created_at > now() - interval '30 days'
--    group by 1 order by 2 desc limit 30;
--   select device, count(*) from public.inflaatio_analytics
--    where event_type = 'page_view' and created_at > now() - interval '30 days'
--    group by 1 order by 2 desc;
-- Old rows (before the new site) also contain event types session_end,
-- chart_interaction, contact_form, cookie_accept and cookie_decline; filter on
-- event_type = 'page_view' to compare periods. They age out with the retention job.
